### ISSUE TITLE
Consider renaming primary module: DistributedActors

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#1043]
It is frequently brought up in the community that the name is very confusing... Technically it is more of a clustering library.

We may consider a rename while we can.

**Comment by ktoso** [comment]
I'm currently leaning towards calling the module `DistributedCluster` since it looks good and explains well what we provide.

It is an extension of the `Distributed` module in swift, by providing the Cluster feature. The primary type of this library is the `ClusterSystem`.

**Comment by tomerd** [comment]
+1 on the proposed named @ktoso 

should we also rename the repository?

**Comment by ktoso** [comment]
Not sure about package, it might give us more freedom to explore things with the generic name tbh, even if we'd split off into separate packages later on -- like a client/server extension to the cluster etc. Though it's all cluster related; so yeah if it's on the table we should perhaps still reconsider -- I was thinking it may be too touchy to rename the package, but maybe not?
