### ISSUE TITLE
Application crashes with fatal error when I subscribe to receptionist.listing updates

### ISSUE THREAD

**Issue by ilova-bazis** [apple/swift-distributed-actors#1053]
Commit hash: 811d2e88a12db8477a0edde6311c1299102314d3

Context:
Application crashes with fatal error when I subscribe to receptionist updates.
For example doing:
```swift
for await testActor in await app.cluster.receptionist.listing(of: .testActor) {
     debugPrint("TestActor added", testActor)
}
```
will result in fatal error
```
DistributedActors/DistributedReceptionist.swift:401: Fatal error: It should not be possible for a version vector to be concurrent with a PAST version of itself before the merge
   Previously: [uniqueNode:sact://firstNode@127.0.0.1:8081: 1]
   Current: [uniqueNode:sact://firstNode@127.0.0.1:8081: 1, uniqueNode:sact://secondNode@127.0.0.1:8082: 1]
```

Steps to reproduce:
1. In your code subscribe to receptionist updates `await app.cluster.receptionist.listing(of: .testActor)`
2. Run two nodes `firstNode` and `secondNode`
3. Create distributed actors randomly either on `firstNode` or `secondNode` after few tries you should get the error.

OS and Swift version:
Apple Swift version 5.7-dev (LLVM d5f117e38620783, Swift d8b7ece39940996)
Target: x86_64-apple-macosx13.0

MacOS Ventura 13.0
Darwin Kernel Version 22.0.0: Wed Jul 20 01:51:06 PDT 2022; root:xnu-8792.0.188.141.3~2/RELEASE_X86_64 x86_64

**Comment by ktoso** [comment]
Thanks for reporting, good timing as I'm focusing on hardening that receptionist rewrite right now -- thanks!

**Comment by ktoso** [comment]
Thanks for reporting, silly bug now fixed on main and will be released in beta.3 soon
