### ISSUE TITLE
Unable to Generate Docs

### ISSUE THREAD

**Issue by spprichard** [apple/swift-distributed-actors#1162]
After cloning repo, from main branch, following the directions in the readme, running 
`./scripts/docs/generate_docc.sh` 
results in the follow error

```
branch 'gh-pages' set up to track 'origin/gh-pages'.
Switched to a new branch 'gh-pages'
./scripts/docs/generate_docc.sh: line 71: ci: command not found
``` 

Running on MacOS 14.6.1

**Comment by akbashev** [comment]
@spprichard guess it should be `git add $version; commit -m "Update documentation: $version"` rather than ci in script... 
@ktoso any reason why ci is used? 🤔

**Comment by ktoso** [comment]
Sounds like a mistake, ci is just "git commit", wanna send in a fix?
