### ISSUE TITLE
Make Membership.member(byUniqueNodeID) O(1)

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#678]
We use this lookup a lot during serialization of membership gossips and in general it just should be _O(1)_.

This is possible to do because:

- storage is `[UniqueNode: Member]`
- we need a wrapper type for they key that we can use equals on by using just the `UniqueNodeID`

**Comment by ktoso** [comment]
Or perhaps doesn't really matter as the collection in reality is usually < 100 nodes...
It could be far bigger but folks don't really cross 1k nodes with such clusters

**Comment by PopFlamingo** [comment]
From a [quick and dirty benchmark](https://gist.github.com/PopFlamingo/6fc60870fa5b463a9daab82d08fe4db3), it seems that the overhead of `Dictionary` only pays off when the lookup is done on more than 40-50 elements.
In all cases I suppose this only really matters if lookups are frequent enough that their cost becomes non negligible.

**Comment by ktoso** [comment]
Thanks for looking into it, to be honest this is probably fine -- let's close out for now.
