### ISSUE TITLE
Since DocC now ships in toolchains, adjust scripts/docs/generate... to not have to download/build docc

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#856]
We used to have to pull, build and use the in-place build docc since it did not ship with the toolchain.

Now it does, so we can adjust the scripts -- they can just invoke `docc` available in the toolchains 👍 

More info: https://forums.swift.org/t/swift-docc-is-now-included-in-swift-toolchains-for-both-macos-and-linux/53284/2

**Comment by shilpeegupta14** [comment]
will add a new clean pull request.
