### ISSUE TITLE
Rename ActorSystem since it gets confusing with the ActorSystem typealias in Swift DA

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#879]
* ActorSystem → ClusterSystem
* Might need to rename or get rid of <system.cluster> since maybe folks will now store it as let cluster = ClusterSystem()

This is started on prepare-5.7 just need to go all the way

**Comment by yim-lee** [comment]
Discussed with @ktoso, for this issue, we will:

- [ ] Rename `ActorSystem` -> `ClusterSystem` (rename file also)
- [ ] Merge `ClusterSettings` into `ClusterSystemSettings` (rename file also)

We will not rename `system.cluster` but will revisit later in https://github.com/apple/swift-distributed-actors/issues/892.

The `enabled` flag in `ClusterSettings` should be removed. That work is covered by https://github.com/apple/swift-distributed-actors/issues/880.

**Comment by ktoso** [comment]
That all sounds great, thank you for looking into these!

**Comment by ktoso** [comment]
Awesome, thank you!
