### ISSUE TITLE
FAILED: DistributedReceptionist test_receptionist_listing_shouldRespondWithRegisteredRefsForKey

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#953]
Something fishy going on with `listing` API, check the `test_receptionist_listing_shouldRespondWithRegisteredRefsForKey`.

**Comment by yim-lee** [comment]
The test runs successfully if wrapped in `try runAsyncAndBlock` and remove `async` keyword from the test method, but ideally the test should run without these changes.
