### ISSUE TITLE
Attaching region metadata to a distributed actor

### ISSUE THREAD

**Issue by PopFlamingo** [apple/swift-distributed-actors#983]
Some use cases might require to be aware of the region a specific actors lives in, for instance in distributed matchmaking where region preferences matter for delays or even networking costs for the host.

I was wondering what is the best way to attach such information to actors of the cluster system?

Thank you

**Comment by ktoso** [comment]
I like the example case of "region", thanks for bringing it up :)

We're making ways to attach metadata to an `ActorID` public now, so I think that'd address this... Will link the related PR here soon

**Comment by PopFlamingo** [comment]
@ktoso Thank you, awesome!

**Comment by ktoso** [comment]
I'll add some more docs and integrate with receptionist soon as well 👍
